### ISSUE TITLE
Needs a man page

### ISSUE THREAD

**Issue by rhatdan** [sallyom/Register#7]

**Comment by sallyom** [comment]
added

**Comment by rhatdan** [comment]
make install DESTDIR=/tmp/dan1
go build -v -o oci-registerMachine
github.com/godbus/dbus
_/home/dwalsh/Register
go get github.com/cpuguy83/go-md2man
go-md2man -in "oci-registerMachine.1.md" -out "oci-registerMachine.1"
gzip oci-registerMachine.1
install -d -m 0755 /tmp/dan1/usr/libexec/docker/hooks.d
install -m 755 oci-registerMachine /tmp/dan1/usr/libexec/docker/hooks.d
cp oci-registerMachine.1.gz /usr/share/man/man1
cp: cannot create regular file ‘/usr/share/man/man1/oci-registerMachine.1.gz’: Permission denied
Makefile:32: recipe for target 'install' failed
make: **\* [install] Error 1

Broken.

**Comment by rhatdan** [comment]
Can we get the path generated on the fly?  Since we have HOOKSDIR defined in the makefile.

**Comment by sallyom** [comment]
sudo make install ok?

**Comment by rhatdan** [comment]
Well yes but that is not the way rpm works,  You need DESTDIR support.  You should also use install not cp.

**Comment by rhatdan** [comment]
Use sed to switch the HOOKSDIR in the man page to give you the path to HOOKCDIR>

**Comment by sallyom** [comment]
I updated, added DESTDIR support
